services:
  postgres:
    container_name: inss_calculo_pg
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
    ports:
      [5432:5432]
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: inss_calculo_redis
    image: redis:6.2.1
    ports:
      [6379:6379]
volumes:
  postgres_data: